version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-2
    IMAGE_REPO_NAME: backend-repo
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.10

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 672897707467.dkr.ecr.ap-south-2.amazonaws.com

  build:
    commands:
      - echo Build React frontend
      - cd frontend
      - npm install
      - npm run build
      - cd ..

      - echo Upload frontend to S3
      - aws s3 sync frontend/build s3://fullstack-react-frontend1

      - echo Build backend Docker image
      - docker build -t $IMAGE_REPO_NAME ./backend
      - docker tag $IMAGE_REPO_NAME:latest 672897707467.dkr.ecr.ap-south-2.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo Push Docker image
      - docker push 672897707467.dkr.ecr.ap-south-2.amazonaws.com/$IMAGE_REPO_NAME:latest
